services:
  server:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    volumes:
      - server-data:/app/server/data
  client:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - server
volumes:
  server-data: {}