name: Deploy to Render
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Server Service
        uses: JorgeLNJunior/render-deploy@v1.4.6
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID_SERVER }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true # Optional: Clear Render's build cache
          wait_deploy: true
          github_deployment: true
          deployment_environment: 'production' # e.g., production, staging
          github_token: ${{ secrets.PAT_TOKEN }}

      - name: Deploy Client Static Site
        uses: JorgeLNJunior/render-deploy@v1.4.6
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID_CLIENT }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true # Optional: Clear Render's build cache
          wait_deploy: true
          github_deployment: true
          deployment_environment: 'production' # e.g., production, staging
          github_token: ${{ secrets.PAT_TOKEN }}
