name: Build & Push Docker Images
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image names
        id: meta
        run: |
          REPO=${GITHUB_REPOSITORY##*/}
          echo "client=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${REPO}-client" >> $GITHUB_OUTPUT
          echo "server=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${REPO}-server" >> $GITHUB_OUTPUT

      - name: Build client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: |
            ${{ steps.meta.outputs.client }}:latest
            ${{ steps.meta.outputs.client }}:${{ github.sha }}

      - name: Build server
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: |
            ${{ steps.meta.outputs.server }}:latest
            ${{ steps.meta.outputs.server }}:${{ github.sha }}
